### ISSUE TITLE
Question about main boards.

### ISSUE THREAD

**Issue by 3DCreator-droid** [3DChameleon/3DChameleonMk4#4]
I thought about buying one, then said I would do it later. I came back to the site to find that it is no longer in a kit you can buy, but is now open source. Here are a few questions I have:

1) What is the best (and least expensive) mainboard to use if you are building it yourself?

2) Could I use an old Ender 3 or CR-10 stock mainboard and flash the firmware to that? (this is important, as I could buy a cheap ender 3 and get all the motors, cables, and endstops I need.)

3) I am not the most advanced, so what is the simplest way to setup these mainboards, as they have more than two motor cable slots, and more than one endstops slot.

**Comment by wjsteele** [comment]
I hate to argue you on this, but I'm not sure what's so complicated about it... it's by far the least expensive (under $20 or far less) and easiest solution to implement (it's all plug and play.)  You literally won't find anything easier and there are dozens of tutorials on YouTube about it.

See here for examples: https://www.youtube.com/results?search_query=cnc+shield

As for other main boards, you're at the mercy of them publishing the schematics, and you'd have to recompile the firmware for their specific board's CPU after you update all the pins.  This is a task that is far harder than simply using the CNC shield as recommended... they already use the same CPU and you only need to change the pin numbers using an off the shelf Arduino.

**Comment by wjsteele** [comment]
I might add, here's a deal for less than $2 shipped!

https://www.aliexpress.us/item/3256806544255538.html

**Comment by Gazorp7734** [comment]
Note to Bill: Since you are moderating this forum. Feel free to move this comment if it would do more good if in another place. Or delete it. Your choice. Sorry if this is long-winded, but I have been doing a lot of studying.

From my time doing M$ Tech Support, I learned that to find a solution, you need to look at previous solutions and decide which parts apply to the current problem. Grab the good parts and combine them to give the answer to the current problem. In GitHub, that means open every hyperlink and comment listed on the topic. Answers are important, but so are the questions. Some questions in time will reveal answers you would give.

I hope no one has to correct me, but the following is my interpretation.
The original question was about the main board or brain of the 3D Chameleon. Whether the board is an original Chameleon board or an Arduino, it needs to monitor the time that a limit switch is pressed to cause a selector or filament drive to run. When the selector is positioned, the filament drive can be run to either advance or retract the filament. The direction of rotation of the motor is based on whether the filament path is to the left of the drive or to the right. With 4 filaments, the choice is simpler. With 8 filaments, the G-Code will have additional lines to identify which filament drive to run. The Chameleon brain has to only monitor limit switch press and then execute movement based on what the G-Code from the slicer is asking for.

I actually have a new Chameleon 4 color unit in transit, just in case I can't make my 8 filament Arduino project work.

I have a FlashForge 5M Pro fresh out of the box. It will update its firmware and there is an Official Firmware that gives a locked down, primitive version of Klipper. There are at least 2 more Klipper versions that are community produced, which claim to be improvements for my printer. This printer is supposed to perform very well with Orca Slicer, which is claimed to be Prusa on steroids. We'll see soon enough.

As I understand it, the Slicer software maintains information needed to motivate the Chameleon to do filament changes as needed for the job it is given. It will command the print head to press the switch to tell Chameleon what to do. If correct, the Chameleon will not know or care that the printer is running Klipper. Klipper code on the Chameleon may be wanted if connected to a non Klipper printer.

I am concentrating on Arduino only. The shields are needed for the brains to do anything.  Examples of Arduino brains are Nano or Uno. The shields hold the stepper drivers and have different versions. I'm concentrating more on the V4, which also has pinout connections for OLED and controlling the filament clipper servo.  

Liam Pulido is very knowledgeable and worth opening every hyperlink and comment. I will definitely try to implement the coding for filament changes, It should cut down on printer poop and color purges.
https://www.3dchameleon.com/group/support/discussion/6932ef55-2450-4e6e-a010-b69ca9242f26  

While following Bill's advice to look on the web for information, I found 2 sources not directly related to Chameleon but are good info for Arduino and Stepper Motors. I try to never look at only one source. Knowing more about stepper motors and Arduino programming is very important.

The first may be hard to understand, but has a lot of good information.
Stepper Motors and Arduino - The Ultimate Guide 
https://www.youtube.com/watch?v=7spK_BkMJys

The second is easy to understand, has humor and good recommendations. 
Control a NEMA 17 Stepper Motor with A4988 Driver and Arduino - Full Guide
https://www.youtube.com/watch?v=wcLeXXATCR4

First is to get Thermal Adhesive to replace the Double sided tape on the heat sinks, otherwise they will fall off and short pins. I got a tube from Amazon. The next is to set the potentiometers on the motor driver boards and shows how to do it. Also, to confirm pin pairings so you can know if the wires need to be moved so they conform to the pinouts on the shield. She did this on a Starter Kit Breadboard. So I ordered one. It comes with a UNO Board. I will use it to set the potentiometers on the driver boards and test my stepper motors. I have only one Nano board and V4 shield that came on a slow boat from China. If I mess up on the breadboard, the Nano will never know. She has good examples for code for running the motors, and I will use that to prove there is no problem with my motors. By testing on the breadboard, not only will the motors and drivers be proven good, but if the known good parts don't work, I will know there is a problem with either the NANO or the Shield board.
